# Generated by Django 4.1.7 on 2023-03-15 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 14, 10, 5, 20449)),
        ),
    ]
